// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/applications": {
            "get": {
                "description": "Returns list of configured applications with their profiles",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config Properties"
                ],
                "summary": "Get applications list",
                "responses": {
                    "200": {
                        "description": "Returned successfully list of configured applications with their profiles",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ApplicationWithProfiles"
                            }
                        }
                    }
                }
            }
        },
        "/{application}/{profile}": {
            "put": {
                "description": "Adds new property for defined application and profile. If property is already existed then replace it with new one.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Config Properties"
                ],
                "summary": "Add new property",
                "parameters": [
                    {
                        "type": "string",
                        "description": "application",
                        "name": "application",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profile",
                        "name": "profile",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON mapping key string to value string",
                        "name": "properties",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Adds new property for defined application and profile. If property is already existed then replace it with new one.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Config Properties"
                ],
                "summary": "Add new property",
                "parameters": [
                    {
                        "type": "string",
                        "description": "application",
                        "name": "application",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profile",
                        "name": "profile",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON mapping key string to value string",
                        "name": "properties",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{application}/{profile}/properties-delete": {
            "post": {
                "description": "Deletes properties for defined application and profile. If properties was not specified would delete all of them.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Config Properties"
                ],
                "summary": "Delete properties",
                "parameters": [
                    {
                        "type": "string",
                        "description": "application",
                        "name": "application",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profile",
                        "name": "profile",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON list with names of properties",
                        "name": "properties",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Properties successfully deleted"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{label}/{name}-{profiles}.json": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Config Properties"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profiles",
                        "name": "profiles",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "label",
                        "name": "label",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": " ",
                        "name": "resolvePlaceholders",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{label}/{name}-{profiles}.properties": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Config Properties"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profiles",
                        "name": "profiles",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "label",
                        "name": "label",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": " ",
                        "name": "resolvePlaceholders",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{label}/{name}-{profiles}.yaml": {
            "get": {
                "description": "Returns YAML formatted configuration for application and profiles",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Config Properties"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profiles",
                        "name": "profiles",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "label",
                        "name": "label",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": " ",
                        "name": "resolvePlaceholders",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{label}/{name}-{profiles}.yml": {
            "get": {
                "description": "Returns YAML formatted configuration for application and profiles",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Config Properties"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profiles",
                        "name": "profiles",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "label",
                        "name": "label",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": " ",
                        "name": "resolvePlaceholders",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{name}-{profiles}.json": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Config Properties"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profiles",
                        "name": "profiles",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": " ",
                        "name": "resolvePlaceholders",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{name}-{profiles}.properties": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Config Properties"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profiles",
                        "name": "profiles",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": " ",
                        "name": "resolvePlaceholders",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{name}-{profiles}.yaml": {
            "get": {
                "description": "Returns YAML formatted configuration for application and profiles",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Config Properties"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profiles",
                        "name": "profiles",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": " ",
                        "name": "resolvePlaceholders",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{name}-{profiles}.yml": {
            "get": {
                "description": "Returns YAML formatted configuration for application and profiles",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Config Properties"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "application",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profiles",
                        "name": "profiles",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": " ",
                        "name": "resolvePlaceholders",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{name}/{profiles}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config Properties"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profiles",
                        "name": "profiles",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Environment"
                        }
                    }
                }
            }
        },
        "/{name}/{profiles}/{label}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config Properties"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "profiles",
                        "name": "profiles",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "label",
                        "name": "label",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Environment"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ApplicationWithProfiles": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "profiles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.Environment": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "profiles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "propertySources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PropertySource"
                    }
                },
                "state": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "model.PropertySource": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "source": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "config-server API",
	Description:      "This is the API documentation for the config-server. With the Config\nServer you have a central place to manage external properties for applications\nacross all environments.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
