# ============== DEPLOYMENT VARIABLES ============================
MONITORING_ENABLED: true
CLOUD_TOPOLOGY_KEY: kubernetes.io/hostname
READONLY_CONTAINER_FILE_SYSTEM_ENABLED: true

# ============== SERVICE VARIABLES ============================

SERVICE_NAME: "core-legacy-api"
SSL_SECRET: "defaultsslcertificate"
CLIENT_SECRET: "/etc/secret"
GATEWAY_URL: "http://internal-gateway-service:8080"
MONITORING_INSTALL: true
ALLOWED_HEADERS: ''
CLOUD_ADMIN_EMAIL: "TestTenantManagementGroup@netcracker.com"
EMAIL_FROM: "no-reply@openshift.sdntest.netcracker"
EMAIL_HOST: "iplanet.netcracker.com"
EMAIL_PASSWORD: ''
EMAIL_USER: ''

HTTP_BUFFER_HEADER_MAX_SIZE: 10240

KUBERNETES_M2M_ENABLED: false


