microservice:
  name: core-legacy-api
  namespace: ${MICROSERVICE_NAMESPACE}

consul.url: ${CONSUL_URL}

http:
  server:
    bind: ":8080"

baseline.fetch.properties: tenant.default.id,bss.tenant.default-id

