kind: Deployment
apiVersion: apps/v1
metadata:
  name: '{{ .Values.SERVICE_NAME }}'
  labels:
    name: '{{ .Values.SERVICE_NAME }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: '{{ .Values.SERVICE_NAME }}'
  template:
    metadata:
      labels:
        name: '{{ .Values.SERVICE_NAME }}'
    spec:
      containers:
        - name: '{{ .Values.SERVICE_NAME }}'
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          image: '{{ .Values.IMAGE_REPOSITORY }}:{{ .Values.TAG }}'
          args:
            - '/app/core-legacy-api'
          env:
            - name: MICROSERVICE_NAME
              value: '{{ .Values.SERVICE_NAME }}'
            - name: CLOUD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONSUL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: config-server-consul-token
                  key: token
            - name: GATEWAY_URL
              value: '{{ .Values.GATEWAY_URL}}'
            - name: XNIO_IO_THREAD
              value: '{{ .Values.XNIO_IO_THREAD }}'
            - name: XNIO_WORK_THREAD
              value: '{{ .Values.XNIO_WORK_THREAD }}'
            - name: TRACING_ENABLED
              value: '{{ .Values.TRACING_ENABLED }}'
            - name: TRACING_HOST
              value: '{{ .Values.TRACING_HOST }}'
            - name: TRACING_SAMPLER_PROBABILISTIC
              value: '{{ .Values.TRACING_SAMPLER_PROBABILISTIC }}'
            - name: LOG_LEVEL
              value: '{{ .Values.LOG_LEVEL }}'
            - name: ALLOWED_HEADERS
              value: '{{ .Values.ALLOWED_HEADERS }}'
            - name: API_DBAAS_ADDRESS
              value: '{{ .Values.API_DBAAS_ADDRESS }}'
            - name: CLOUD_PUBLIC_HOST
              value: '{{ .Values.CLOUD_PUBLIC_HOST }}'
            - name: CLOUD_PRIVATE_HOST
              value: '{{ .Values.CLOUD_PRIVATE_HOST }}'
            - name: EMAIL_HOST
              value: '{{ .Values.EMAIL_HOST }}'
            - name: EMAIL_FROM
              value: '{{ .Values.EMAIL_FROM }}'
            - name: CLOUD_ADMIN_EMAIL
              value: '{{ .Values.CLOUD_ADMIN_EMAIL }}'
            - name: PRIVATE_GATEWAY_URL
              value: '{{ .Values.PRIVATE_GATEWAY_URL }}'
            - name: PUBLIC_GATEWAY_URL
              value: '{{ .Values.PUBLIC_GATEWAY_URL }}'
            - name: CLOUD_API_HOST
              value: '{{ .Values.CLOUD_API_HOST }}'
            - name: CLOUD_API_PORT
              value: '{{ .Values.CLOUD_API_PORT }}'
            - name: CLOUD_PROTOCOL
              value: '{{ .Values.CLOUD_PROTOCOL }}'
            - name: NC_DIAGNOSTIC_MODE
              value: '{{ .Values.NC_DIAGNOSTIC_MODE }}'
            - name: NC_DIAGNOSTIC_AGENT_SERVICE
              value: '{{ .Values.NC_DIAGNOSTIC_AGENT_SERVICE }}'
            - name: BASELINE_PROJ
              value: '{{ .Values.BASELINE_PROJ }}'
            - name: CONSUL_ENABLED
              value: '{{ .Values.CONSUL_ENABLED | default false }}'
                        {{- if .Values.CONSUL_ENABLED }}
            - name: CONSUL_URL
              value: '{{ .Values.CONSUL_URL }}'
                        {{- end }}
            - name: HTTP_BUFFER_HEADER_MAX_SIZE
              value: '{{ .Values.HTTP_BUFFER_HEADER_MAX_SIZE }}'
            - name: KUBERNETES_M2M_ENABLED
              value: '{{ .Values.KUBERNETES_M2M_ENABLED }}'
          volumeMounts:
            -   name: client-credentials
                mountPath: '{{ .Values.CLIENT_SECRET }}'
                readOnly: true
            -   name: '{{ .Values.SSL_SECRET }}'
                mountPath: /tmp/cert/{{ .Values.SSL_SECRET }}
          livenessProbe:
            httpGet:
              path: "/health"
              port: web
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: "/health"
              port: web
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          resources:
            limits:
              cpu: '1'
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
      volumes:
        - name: client-credentials
          secret:
            secretName: 'core-legacy-api-client-credentials'
        - name: '{{ .Values.SSL_SECRET }}'
          secret:
            secretName: '{{ .Values.SSL_SECRET }}'