apiVersion: v1
kind: Secret
metadata:
  name: config-server-email-secret
  namespace: '{{ .Values.NAMESPACE }}'
  labels:
    app.kubernetes.io/part-of: 'Cloud-Core'
    app.kubernetes.io/managed-by: 'saasDeployer'
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
stringData:
  username: '{{ .Values.EMAIL_USER }}'
  password: '{{ .Values.EMAIL_PASSWORD }}'