// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\kana0626\IdeaProjects\core-legacy-api\core-legacy-api-impl\config\controller.go
//
// Generated by this command:
//
//	mockgen -source=C:\Users\kana0626\IdeaProjects\core-legacy-api\core-legacy-api-impl\config\controller.go -destination=C:\Users\kana0626\IdeaProjects\core-legacy-api\core-legacy-api-impl\config\mock-service\mocks.go
//

// Package mock_controller is a generated GoMock package.
package mock_controller

import (
	context "context"
	"core-legacy-api/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConfigService is a mock of ConfigService interface.
type MockConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockConfigServiceMockRecorder
	isgomock struct{}
}

// MockConfigServiceMockRecorder is the mock recorder for MockConfigService.
type MockConfigServiceMockRecorder struct {
	mock *MockConfigService
}

// NewMockConfigService creates a new mock instance.
func NewMockConfigService(ctrl *gomock.Controller) *MockConfigService {
	mock := &MockConfigService{ctrl: ctrl}
	mock.recorder = &MockConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigService) EXPECT() *MockConfigServiceMockRecorder {
	return m.recorder
}

// AddProperties mocks base method.
func (m *MockConfigService) AddProperties(ctx context.Context, application, profile string, properties map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProperties", ctx, application, profile, properties)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProperties indicates an expected call of AddProperties.
func (mr *MockConfigServiceMockRecorder) AddProperties(ctx, application, profile, properties any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProperties", reflect.TypeOf((*MockConfigService)(nil).AddProperties), ctx, application, profile, properties)
}

// DeleteProfile mocks base method.
func (m *MockConfigService) DeleteProfile(ctx context.Context, application, profile string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProfile", ctx, application, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProfile indicates an expected call of DeleteProfile.
func (mr *MockConfigServiceMockRecorder) DeleteProfile(ctx, application, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProfile", reflect.TypeOf((*MockConfigService)(nil).DeleteProfile), ctx, application, profile)
}

// DeleteProperties mocks base method.
func (m *MockConfigService) DeleteProperties(ctx context.Context, application, profile string, propertiesToDelete []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProperties", ctx, application, profile, propertiesToDelete)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProperties indicates an expected call of DeleteProperties.
func (mr *MockConfigServiceMockRecorder) DeleteProperties(ctx, application, profile, propertiesToDelete any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProperties", reflect.TypeOf((*MockConfigService)(nil).DeleteProperties), ctx, application, profile, propertiesToDelete)
}

// FindAll mocks base method.
func (m *MockConfigService) FindAll(ctx context.Context) ([]model.ConfigProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]model.ConfigProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockConfigServiceMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockConfigService)(nil).FindAll), ctx)
}

// FindByApplicationAndProfile mocks base method.
func (m *MockConfigService) FindByApplicationAndProfile(ctx context.Context, serviceName, profile string) (model.ConfigProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByApplicationAndProfile", ctx, serviceName, profile)
	ret0, _ := ret[0].(model.ConfigProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByApplicationAndProfile indicates an expected call of FindByApplicationAndProfile.
func (mr *MockConfigServiceMockRecorder) FindByApplicationAndProfile(ctx, serviceName, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByApplicationAndProfile", reflect.TypeOf((*MockConfigService)(nil).FindByApplicationAndProfile), ctx, serviceName, profile)
}
